import { betterAuth } from "better-auth";
import { drizzleAdapter } from "better-auth/adapters/drizzle";
import { nextCookies } from "better-auth/next-js";

import { db } from "@/db";
import { accounts, sessions, users, verifications } from "@/db/schema";

/**
 * Authentication, self-hosted inside this Next.js app.
 *
 * No separate auth server: better-auth runs as route handlers under
 * /api/auth/*, and sessions live in the same Postgres database as everything
 * else. One process, one database, one place to look when something is wrong.
 *
 * The schema is declared in db/schema.ts rather than generated by better-auth's
 * own migrator, so there is a single migration path. `camelCase: true` is what
 * ties the two together: our Drizzle table properties are camelCase, matching
 * better-auth's field names exactly.
 */

function required(name: string, value: string | undefined): string {
  if (!value || value.trim() === "") {
    // Failing loudly at boot beats signing sessions with an empty secret and
    // discovering it when someone forges one.
    throw new Error(
      `${name} is not set. Sessions cannot be signed without it — see .env.example.`,
    );
  }
  return value.trim();
}

/**
 * SameSite=None requires the Secure flag, and Secure requires HTTPS. Setting
 * it on a plain-http deployment means browsers silently drop the cookie and
 * nobody can stay signed in, so it is only honoured when the app is served
 * over HTTPS.
 */
function cookieAttributes() {
  const baseUrl = process.env.BETTER_AUTH_URL ?? "http://localhost:3000";
  const secure = baseUrl.startsWith("https://");
  const requested = (process.env.COOKIE_SAME_SITE ?? "lax").toLowerCase();

  const sameSite: "lax" | "strict" | "none" =
    requested === "none" && secure
      ? "none"
      : requested === "strict"
        ? "strict"
        : "lax";

  return { sameSite, secure, httpOnly: true, path: "/" } as const;
}

export const auth = betterAuth({
  appName: "GOP_IMPORT",
  secret: required("JWT_SECRET", process.env.JWT_SECRET),
  baseURL: process.env.BETTER_AUTH_URL ?? "http://localhost:3000",

  database: drizzleAdapter(db, {
    provider: "pg",
    camelCase: true,
    schema: {
      user: users,
      session: sessions,
      account: accounts,
      verification: verifications,
    },
  }),

  emailAndPassword: {
    enabled: true,
    autoSignIn: true,
    // Long enough to matter, short enough that people do not write it down.
    minPasswordLength: 10,
    maxPasswordLength: 128,
  },

  session: {
    expiresIn: 60 * 60 * 24 * 30,
    updateAge: 60 * 60 * 24,
  },

  user: {
    additionalFields: {
      role: { type: "string", input: false, defaultValue: "member" },
      licenseKeyId: { type: "string", input: false, required: false },
    },
  },

  advanced: {
    defaultCookieAttributes: cookieAttributes(),
  },

  // Must be last: it is what lets route handlers set cookies on the response.
  plugins: [nextCookies()],
});

export type Auth = typeof auth;
